enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Twitter]
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
direct-dlurl = "https://github.com/NullCode1337/piko-magisk-module/releases/download/1/com.twitter.android-12.7.1-release.0-all.apkm"
build-mode = "module"
version = "12.7.1-release.0"
include-stock = "split"

[Instagram]
build-mode = "module"
cli-source = "MorpheApp/morphe-cli"
patches-source = "crimera/piko"
rv-brand = "Piko"
include-stock = "split"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
direct-dlurl = "https://github.com/NullCode1337/piko-magisk-module/releases/download/1/com.instagram.android-435.0.0.37.76-arm64-v8a.apkm"
version = "435.0.0.37.76"
